name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  device_preview: ^1.1.0
  iconly: ^1.0.1
  fpdart: ^1.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  provider: ^6.1.2
  dio: ^5.6.0
  lottie: ^3.1.2
  flutter_otp_text_field: ^1.2.0
  build_runner: any
  flutter_secure_storage: ^9.2.2
  flutter_otp_text_field: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/on1.json
    - images/load.json
    - images/background.png